### ISSUE TITLE
Explanation about the underlying rationale in wealthy-consciousness relationship

### ISSUE THREAD

**Issue by sammo3182** [fsolt/class_consciousness#14]
"(W)hy do wealthy people become more 'class conscious' in response to greater inequality? Again, I realize space constraints are severe but at least speculate on the difference. Is it that the wealthy actually have more information?"

Perhaps we should cite our "Economic Inequality and Belief in Meritocracy in the United States"?

**Comment by fsolt** [comment]
I've no qualm with self-citing here _if_ our piece does actually help provide an answer to the question, Erico.  The fact that a paper is in a "lower-tier journal" is definitely _not_ a reason to not cite to it (otherwise, at the limit, APSR pieces wouldn't be able to cite to anything at all!).

**Comment by dongericoyu** [comment]
True. Thanks for the insight Fred :)

**Comment by dongericoyu** [comment]
Dear all:

Sorry for the delayed response. I first added some sentences (mostly from point#3 below) in the revised draft, but I later deleted them since I look at the results again and have a second-thought.  I want to double-check with you and see which is the best response.

I don't think citing our Meritocracy piece helps to provide an answer to Reviewer 1's question. First, most of the theoretical argument we presented in Merit are also presented in Class-Consciousness. Second, based on the theory of our piece and the relative power theory, the rich have more resources, which include information, and thus can internalize the poor's belief through media, culture and other social institutions controlled by the rich elites. **However, the data of the either piece do not directly test the argument that information or knowledge has a positive relationship with the perception of inequality, belief of meritocracy, and self class consciousness.**

**The only possible reference of political knowledge is education. Neither it is a perfect reference, nor we show a consistent result in the two pieces: in Figure 3 of the Meritocracy piece, education is positive and significant, supporting the argument; in Figure 1 of this piece, education is negative and insignificant. If more educated people are less likely to believe the US as divided into the "have" and "have-nots", then we would have a strange inference for the right panel of Figure 5: the rich (which has a high correlation with education level) believe they and the people of other income groups are both the "have". ** 

So I think we just cannot use the Merit piece to answer the reviewer 1's question.

Below are my responses to be included in the memo:

1. We think the reviewer 1 expand our result in explaining something beyond the paper's capability. In general, this article do not directly address the question "why the rich/wealthy become more "class conscious". As we point out in the last two paragraph , we prove the false class consciousness, the self-perception, rather than the perception of the inequality context,  existed among the poor with regardless of contexts of income inequality.  However, proving this false class consciousness argument does not necessarily requires us to answer the whether (or why in Reviewer 1's comment) the rich develop a class consciousness.  


2.  According to the result of the right panel of Figure 5, which shows median or higher income individuals are less likely to identify themselves as "have-nots" as the inequality becomes more severe. However, simply rejecting the self-consciousness of "have-nots" (or accepting themselves as "have") do not prove they have a strong social class consciousness. Because we do not know how they perceive the others of different income groups. In fact, as we  see in Figure 1, income has a negative relationship with the perception of a divided US. In other words, the rich may identify themselves as the "haves", but not accepting the fact there is . It is also different from the class consciousness that Georg Lukács (1920) defines.  

(I'm not quite sure my response in Point#2 here is correct, so I provide an alternative response in point #3.) 

3. (If we interpret the result the right panel of Figure 5 as Reviewer 1 does), two possible arguments may explain why the rich have a stronger class consciousness as income inequality increases. First of all, as inequality increases, the rich feel more insecure: they worry about social turmoil, revolution and other violence initiated by the lower class to redistribute their wealth; such a sense of insecurity reinforces their own class consciousness, and they either use different resources and misinformation to instill false-class consciousness to the poor (Jacob and Shapiro, 2000), or create specific institutions (property protection laws, income-defense industry, or political agenda) to protect their wealth (Winters, 2011). Second, as inequality increases, since the rich have more access to information, they are more sensitive to the context, and more likely to develop a self-consciousness of "have".  (Xu and Garand, 2010)    The first argument provides a subjective incentive, and the second argument provides a necessary condition of the formation of class consciousness. 


Reference:
Lukács, György. 1971 [1920]. History and class consciousness; studies in Marxist dialectics. Cambridge, Mass.,: MIT Press.

Jacobs, Lawrence R., and Robert Y. Shapiro. 2000. Politicians Don’t Pander. Chicago: University of Chicago Press

Winters, Jeffrey A. 2011. Oligarchy. Cambridge: Cambridge University Press

**Comment by fsolt** [comment]
Wait a minute, wait a minute---the reviewer is assuming facts not in evidence here (to quote the courtroom drama of your choice).  There is no evidence in our results of a statistically significant increase in class consciousness even among those with the highest incomes: the decline in the predicted probability in the right panel of figure 4 is 14±15 percentage points.  (Errors propagate geometrically; it's actually really hard to judge the statistical significance of the _difference_ between two points by eye.) If we weren't page-restricted, we could point this out to avoid other readers' confusion, but as it stands, this is just fodder for the memo.

**Comment by fsolt** [comment]
Hmm.  On second thought, I'm not really satisfied with my earlier response, given the significant coefficient in logit space and that predicted probabilities depend on the values of the other variables—when other variables are at their medians the pred prob is being constrained by zero.  Sigh.

I still don't think we should speculate on this.  Erico's right that we can't point to our other piece with regard to info, but that's R1's speculation, not ours.  If I were pushed, I'd point to relative power theory: the reason is that what's going on is that those with higher incomes are not fighting the 'reality distortion field' that those with lower incomes are.  But we don't have space, and I don't feel pushed.

**Comment by dongericoyu** [comment]
Thank you for the response Fred. Just clarifying your comments: (1)do you think I should still include a short response (pointing out R1's over-interpretation) in the memo? (2) what do you mean by the "reality distortion field"?

**Comment by fsolt** [comment]
Nope.  And 'RDF' was a reference to the greater ability of the wealthy to shape the attitudes and beliefs of the poor present in contexts of higher inequality.  Also, to Steve Jobs.  But never mind.
