### ISSUE TITLE
Conclusion

### ISSUE THREAD

**Issue by fsolt** [fsolt/class_consciousness#3]

**Comment by dongericoyu** [comment]
I find this comparative study (though dates back to 1979) helps to explain why income has a relatively small effect on self-identification of "have-not" showed in plot 3 and 4: the stratification systems in the US is more based on education and occupational status, rather than ownership of property or authority as other European societies. ([Robinson, Robert and Jonathan Kelley, "Class as Conceived by Marx and Dahrendorf: Effects on Income Inequality and Politics in the United States and Great Britain," _American Sociological Review_, Vol.44, No.1(1979)](http://www.jstor.org/stable/pdf/2094817.pdf?_=1463509708616))

**Comment by fsolt** [comment]
The abstract looks interesting (and promising).  Did you mean to write "to explain why income _inequality_ has a relatively small effect," though?  _Income_ has a big effect in our analyses.
